### GET request to example server
GET http://127.0.0.1:8080/api/gen-playlists/playlists?limit=10&offset=1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhbmRyZW9zZS5tYXJjbzkzQGdtYWlsLmNvbSIsImlhdCI6MTc1NTQyMDMzOSwiZXhwIjoxNzU1NDIzOTM5fQ.BmGLFAbcfbnAv9NB9ZYMMBkFut9PwKprxlH-9Nzmh5zZoDZV0kn2t3V3tEz5IzR5jEpu70GJgJfW7F4OsZRcvA

###

### GET request to example server
GET http://127.0.0.1:8080/api/gen-playlists/playlists
Accept: application/json
Authorization: Bearer pippo

###

### GET request to example server
GET https://api.spotify.com/v1/me/playlists
Accept: application/json
Authorization: Bearer BQAEcP3GNX4bTy0KFVPBFiOJJHMxS77eW0fzizH11DHdYvgc25oWGThah_utYtO9LTEJ6HHDlBthCM9UR89ow94eTqYdAvfcsq5RnKRVTcNpKTCjc_cvMPeuMTNpXwox4L_9VeY_D-aLH8gVewstdbWCMAEAd9eJ8Hx5ZSpeEGyz1JKTzT6nd6WBKHzpEClwO9EFh_xGqXnrLFpVobZw957OjEZWvrpasFik6NqIJw

###


### Exchange code for token (form-urlencoded)
POST https://accounts.spotify.com/api/token
Content-Type: application/x-www-form-urlencoded
Accept: application/json

client_id = {{clientId}} &
grant_type = authorization_code &
code = {{code}} &
client_secret = {{clientSecret}} &
redirectUri = {{redirectUri}}


###




###

